from typing import Any

from pydantic import BaseModel, Field, field_validator


class RAGRequest(BaseModel):
    """
    Represents a request submitted to the RAG pipeline.
    """

    query: str = Field(
        ...,
        min_length=1,
        description="User question or information request",
    )

    top_k: int = Field(
        default=5,
        ge=1,
        le=20,
        description="Number of relevant chunks to retrieve",
    )

    document_id: str | None = Field(
        default=None,
        description="Optional document ID used to restrict retrieval",
    )

    @field_validator("query")
    @classmethod
    def validate_query(cls, value: str) -> str:
        if not value.strip():
            raise ValueError("Query cannot be empty.")

        return value


class SourceReference(BaseModel):
    """
    Represents a source used to generate a RAG response.
    """

    document_id: str = Field(
        ...,
        description="Unique identifier of the source document",
    )

    document_name: str = Field(
        ...,
        description="Original source document filename",
    )

    chunk_id: int = Field(
        ...,
        description="Chunk number within the document",
    )

    score: float = Field(
        ...,
        description="Similarity score of the retrieved chunk",
    )


class RAGResponse(BaseModel):
    """
    Represents the final response generated by the RAG pipeline.
    """

    answer: str = Field(
        ...,
        description="Generated answer",
    )

    sources: list[SourceReference] = Field(
        default_factory=list,
        description="Sources used to generate the answer",
    )

    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional metadata associated with the response",
    )